# Generated by Django 4.1.13 on 2025-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryId', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('education', models.CharField(max_length=255)),
                ('passout_year', models.CharField(max_length=4)),
                ('course', models.CharField(max_length=255)),
                ('placement', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('currently_working', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('profession', models.CharField(blank=True, choices=[('it', 'IT'), ('non-it', 'Non-IT')], max_length=10, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('pf', models.CharField(blank=True, max_length=3, null=True)),
                ('uan', models.CharField(blank=True, max_length=20, null=True)),
                ('form16', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('address', models.TextField()),
                ('pan_aadhar', models.CharField(max_length=20)),
                ('refer_by', models.CharField(blank=True, max_length=255, null=True)),
                ('referer_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
